### Listar todas las tareas
GET http://127.0.0.1:3000/api/tareas

### Buscar una tarea por id
GET http://127.0.0.1:3000/api/tareas/1

### tareas pendientes
GET http://127.0.0.1:3000/api/tareas/estado/pendiente

### tareas en progreso
GET http://127.0.0.1:3000/api/tareas/estado/en%20progreso

### tareas completadas
GET http://127.0.0.1:3000/api/tareas/estado/completada

### tareas canceladas
GET http://127.0.0.1:3000/api/tareas/estado/cancelada
